#!/bin/python3
#Helpful URL: https://stackoverflow.com/questions/1456269/python-git-module-experiences

import git

def git_commit():
    repo = git.Repo("./test-repo")
    try:
        commit_result = repo.git.commit(m="Commiting via python code")
    except git.exc.GitCommandError:
        print("Possible Nothing To Commit")

        def git_commit2(location, message):
    repo = git.Repo(location)
    return_message = "Possibly Nothing To Commit"
    try:
        repo.git.commit('-m', message)
        return_message = "Successful commit"
    except git.exc.GitCommandError:
        return_message = "Possibly Nothing To Commit"
    return return_message

def git_pull(location):
    repo = git.Repo(location)
    try:
        repo.git.pull()
        return_message = "Repo has had a fresh pull"
    except git.exc.GitCommandError:
        return_message = "Possibly Nothing To Pull"
    return return_message

def git_add(location):
    repo = git.Repo(location)
    try:
        repo.git.add(".")
        return_message = "Files have been git added"
    except git.exc.GitCommandError:
        return_message = "Most likely nothing to add"
    return return_message

def git_push(location):
    repo = git.Repo(location)
    origin = repo.remote(name='origin')
    try:
        result = origin.push()[0].summary
    except git.exc.GitCommandError as e:
        result = e.stderr
    return True, result
